Ejercicio1
Cami12/Induccion-Ruby pull request #1
Opened 2018-05-10 18:53 UTC by Cami12

2018-05-15 20:45 UTC, vatbq requested changes

2018-05-15 20:45 UTC, ValentinaTironi commented on spec/lib/Ejercicio1_spec.rb
> +
Eliminar espacios

2018-05-15 20:46 UTC, vatbq commented on lib/Ejercicio1.rb
> +  end
indentation

2018-05-15 20:46 UTC, vatbq commented on spec/lib/Ejercicio1_spec.rb
> +        expect(o.Words('Hola', 'ComoEstas', '1234568910')).to eq ('1234568910')
Indentation

2018-05-15 20:51 UTC, ValentinaTironi commented on spec/lib/Ejercicio1_spec.rb
> +        expect(o.Words('Hola', 'ComoEstas', '1234568910')).to eq ('1234568910')
Podes usar `let` para guardar los posibles valores y después llamarlos desde el `expect`. Son una especie de variables, investiga en internet, te van a ser de mucha ayuda
**Aplicar en todos los casos**

2018-05-15 20:52 UTC, MatiasCarrara requested changes

2018-05-15 20:52 UTC, MatiasCarrara commented on spec/lib/Ejercicio1_spec.rb
> +      #o.Words(['Hola', 'ComoEstas'])
borrar comentarios

2018-05-15 20:56 UTC, vatbq commented on spec/lib/Ejercicio1_spec.rb
> +    it "What happen when don't put anything" do
single quotes

2018-05-15 20:57 UTC, MatiasCarrara requested changes

2018-05-15 20:57 UTC, MatiasCarrara commented on lib/Ejercicio1.rb
> +  def Words(*palabras)
escribir todo en ingles

2018-05-15 20:57 UTC, MatiasCarrara commented on lib/Ejercicio1.rb
> +class Ejercicio1
correr Rubocop

2018-05-15 21:01 UTC, ValentinaTironi commented on spec/lib/Ejercicio1_spec.rb
> +    it "What happen when two or more words have the same longest" do
En los `it` se escribe que debería pasar en el caso descripto en el `context`, el cual deberías utilizar, allí iría lo que pusiste como descripción de este`it`

2018-05-16 17:11 UTC, lcarozzi requested changes

2018-05-16 17:11 UTC, lcarozzi commented on spec/lib/Ejercicio1_spec.rb
> +    it "What happen when don't put anything" do
@ValentinaTironi las double quotes son necesarias en este caso porque tiene un `'` por el `don't`

2018-05-16 17:11 UTC, lcarozzi commented on spec/lib/Ejercicio1_spec.rb
> +        expect('').to eq ('')
aca estas copmparando lo mismo, deberias llamar a la funcion con vacio y luego comparar.

2018-05-16 17:11 UTC, lcarozzi commented on spec/spec_helper.rb
> +# This file was generated by the `rspec --init` command. Conventionally, all
borra todos los comentarios

2018-05-16 17:11 UTC, lcarozzi commented on lib/Ejercicio1.rb
> +    return mas_grande
la palabra `return` no es necesaria

2018-05-16 17:11 UTC, lcarozzi commented on lib/Ejercicio1.rb
> +  def Words(*palabras)
los metodos se definen en minuscula

2018-05-16 17:11 UTC, lcarozzi commented on lib/Ejercicio1.rb
> +       if palabra.length > mas_grande.length
cuando es posible preferimos hacer todo en una sola linea. https://github.com/bbatsov/ruby-style-guide#if-as-a-modifier

2018-05-16 17:55 UTC, lcarozzi requested changes

2018-05-16 17:55 UTC, lcarozzi commented on spec/lib/Ejercicio1_spec.rb
> +    o = Ejercicio1.new
no es una buena practica definir variables sueltas. Existen dos maneras para referenciar a una variable, una de ellas es usando `let` y la otra es usando `subject`. En particular `subject` se usa cuando es el metodo que estamos probando.

2018-05-29 20:07 UTC, lcarozzi requested changes

2018-05-29 20:07 UTC, lcarozzi commented on lib/ejercicio1.rb
> +module Ejercicio1
usar ingles

2018-05-29 20:07 UTC, lcarozzi commented on lib/ejercicio1.rb
> +      palabra.length > mas_grande.length ? mas_grande = palabra : mas_grande
el else no es necesario

2018-05-29 20:07 UTC, lcarozzi commented on spec/spec_helper.rb
> +# This file was generated by the `rspec --init` command. Conventionally, all
☝️

2018-05-30 19:48 UTC, MatiasCarrara approved these changes

2018-05-30 19:48 UTC, ValentinaTironi commented on lib/ejercicio1.rb
> +    biggest = words1.first
Usa nombres descriptivos en las variables, en este caso podría ser `words`

2018-05-30 19:52 UTC, ValentinaTironi commented on spec/lib/ejercicio1_spec.rb
> +  subject { Exercise1.words(*words1) }
Cuando lo vayas a cambiar, no te olvides de hacerlo acá también

2018-05-31 18:39 UTC, vatbq approved these changes

2018-06-05 16:25 UTC, lcarozzi requested changes

2018-06-05 16:25 UTC, lcarozzi commented on .gitignore
> +.git
agrega los DS files al gitignore

2018-06-05 16:25 UTC, lcarozzi commented on lib/ejercicio1.rb
> +      word.length > biggest.length ? biggest = word : biggest
capaz que esto podria quedar mas claro de otra forma, segui pensando

2018-06-05 16:25 UTC, lcarozzi commented on spec/lib/ejercicio1_spec.rb
> +  context 'What happen when two or more words have the same longest' do
te recomiendo hacer los contextos mas especificos por ejemplo
`context 'With same length words' do`

el contexto no tiene porque siempre empezar con "when"

2018-06-05 16:25 UTC, lcarozzi commented on spec/lib/ejercicio1_spec.rb
> +    it 'Return the first word entered' do
`returns` con "s" porque es la tercera persona del singular: "it".

2018-06-07 19:09 UTC, lcarozzi approved these changes

2018-06-07 19:51 UTC, merged