I upload exercise 3
Cami12/Induccion-Ruby pull request #3
Opened 2018-05-31 17:47 UTC by Cami12

2018-05-31 18:46 UTC, ValentinaTironi commented on lib/ejercicio3.rb
> +        return true
Podes hacer esto en una sola linea

2018-05-31 18:46 UTC, ValentinaTironi commented on spec/ejercicio3_spec.rb
> +    subject { Exercise3.include?(words, character) }
Por qué no nombraste a los parámetros como se le llama en el método?

2018-05-31 18:46 UTC, ValentinaTironi commented on spec/ejercicio3_spec.rb
> +    context 'What happend if exist a one object that belongs in the array' do
pusiste `a one` en el context, quedate con uno solo

2018-05-31 18:46 UTC, ValentinaTironi commented on spec/ejercicio3_spec.rb
> +    context 'If exist a one object but not belongs in the array' do
lo mismo

2018-06-05 16:27 UTC, lcarozzi requested changes
El mensaje de commit deberia ser impersonal, en lugar de "I upload ..." podes poner simplemente "Implement include? method" por ejemplo

2018-06-07 19:10 UTC, lcarozzi approved these changes

2018-06-07 20:03 UTC, merged